/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuizApp_Gui;

import QuizApp_DAO.PerformanceDAO;
import QuizApp_Pojo.StudentScore;
import QuizApp_Pojo.UserProfile;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Sandarbh Taran
 */
public class AdminViewIndividualScoreFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminViewIndividualScoreFrame
     */Color oldcolor;
         public AdminViewIndividualScoreFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("QUIZAPP");
        lblDisplayUsername.setText("Hello "+UserProfile.getUsername());
        loadStudentsList();
    }
         ArrayList<String>studentList;
private void loadStudentsList()
{
    
   try{
       studentList=PerformanceDAO.getStudentList();
       if(studentList.isEmpty()==true)
       {
           JOptionPane.showMessageDialog(null,"! No student appeared for the exam","!NO RECORD FOUND",JOptionPane.INFORMATION_MESSAGE);
           return;
       }
       
       for(String s:studentList)
       {
           cbSelectStudent.addItem(s);
       }
       
   }catch(SQLException ex){
       JOptionPane.showMessageDialog(null,"! DB Error","!ADMIN VIEW INDIVIDUAL SCORE ERROR",JOptionPane.ERROR_MESSAGE);
       ex.printStackTrace();
   }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdminViewIndividualScoreFrame = new javax.swing.JPanel();
        lblDisplayUsername = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        pnlAdminViewIndividualScoreInner = new javax.swing.JPanel();
        lblSelectStudent = new javax.swing.JLabel();
        lblExamId = new javax.swing.JLabel();
        lblSubject = new javax.swing.JLabel();
        lblPercentage = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        cbSelectExam = new javax.swing.JComboBox<>();
        cbSelectStudent = new javax.swing.JComboBox<>();
        txtPercent = new javax.swing.JTextField();
        txtSubject = new javax.swing.JTextField();
        lblScore = new javax.swing.JLabel();
        lblAdminViewIndividualScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlAdminViewIndividualScoreFrame.setBackground(new java.awt.Color(0, 0, 0));

        lblDisplayUsername.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblDisplayUsername.setForeground(new java.awt.Color(0, 255, 0));

        lblLogout.setBackground(new java.awt.Color(0, 0, 0));
        lblLogout.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 153, 51));
        lblLogout.setText("Logout");
        lblLogout.setOpaque(true);
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });

        pnlAdminViewIndividualScoreInner.setBackground(new java.awt.Color(0, 0, 0));
        pnlAdminViewIndividualScoreInner.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "SELECT DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 3, 24), new java.awt.Color(0, 102, 102))); // NOI18N

        lblSelectStudent.setBackground(new java.awt.Color(0, 0, 0));
        lblSelectStudent.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblSelectStudent.setForeground(new java.awt.Color(255, 153, 51));
        lblSelectStudent.setText("SELECT STUDENT");

        lblExamId.setBackground(new java.awt.Color(0, 0, 0));
        lblExamId.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblExamId.setForeground(new java.awt.Color(255, 153, 51));
        lblExamId.setText("SELECT EXAM ID");

        lblSubject.setBackground(new java.awt.Color(0, 0, 0));
        lblSubject.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblSubject.setForeground(new java.awt.Color(255, 153, 51));
        lblSubject.setText("SUBJECT");

        lblPercentage.setBackground(new java.awt.Color(0, 0, 0));
        lblPercentage.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblPercentage.setForeground(new java.awt.Color(255, 153, 51));
        lblPercentage.setText("PERCENTAGE");

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 153, 51));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        cbSelectExam.setBackground(new java.awt.Color(204, 204, 204));
        cbSelectExam.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        cbSelectExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSelectExamActionPerformed(evt);
            }
        });

        cbSelectStudent.setBackground(new java.awt.Color(204, 204, 204));
        cbSelectStudent.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        cbSelectStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSelectStudentActionPerformed(evt);
            }
        });

        txtPercent.setEditable(false);
        txtPercent.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        txtPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPercentActionPerformed(evt);
            }
        });

        txtSubject.setEditable(false);
        txtSubject.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        txtSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminViewIndividualScoreInnerLayout = new javax.swing.GroupLayout(pnlAdminViewIndividualScoreInner);
        pnlAdminViewIndividualScoreInner.setLayout(pnlAdminViewIndividualScoreInnerLayout);
        pnlAdminViewIndividualScoreInnerLayout.setHorizontalGroup(
            pnlAdminViewIndividualScoreInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminViewIndividualScoreInnerLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(pnlAdminViewIndividualScoreInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSelectStudent)
                    .addComponent(lblSubject, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblExamId, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPercentage, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(56, 56, 56)
                .addGroup(pnlAdminViewIndividualScoreInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbSelectExam, javax.swing.GroupLayout.Alignment.LEADING, 0, 219, Short.MAX_VALUE)
                    .addComponent(cbSelectStudent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSubject, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPercent, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(67, 67, 67))
            .addGroup(pnlAdminViewIndividualScoreInnerLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAdminViewIndividualScoreInnerLayout.setVerticalGroup(
            pnlAdminViewIndividualScoreInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminViewIndividualScoreInnerLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(pnlAdminViewIndividualScoreInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectStudent)
                    .addComponent(cbSelectStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(pnlAdminViewIndividualScoreInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExamId)
                    .addComponent(cbSelectExam, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnlAdminViewIndividualScoreInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubject)
                    .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(pnlAdminViewIndividualScoreInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPercentage)
                    .addComponent(txtPercent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizApp_Gui/Images/l&t-logo.PNG"))); // NOI18N

        lblAdminViewIndividualScore.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        lblAdminViewIndividualScore.setForeground(new java.awt.Color(0, 255, 0));
        lblAdminViewIndividualScore.setText("STUDENTS RECORDS");

        javax.swing.GroupLayout pnlAdminViewIndividualScoreFrameLayout = new javax.swing.GroupLayout(pnlAdminViewIndividualScoreFrame);
        pnlAdminViewIndividualScoreFrame.setLayout(pnlAdminViewIndividualScoreFrameLayout);
        pnlAdminViewIndividualScoreFrameLayout.setHorizontalGroup(
            pnlAdminViewIndividualScoreFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminViewIndividualScoreFrameLayout.createSequentialGroup()
                .addGroup(pnlAdminViewIndividualScoreFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminViewIndividualScoreFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDisplayUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAdminViewIndividualScoreFrameLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblScore)
                        .addGap(69, 69, 69)
                        .addComponent(pnlAdminViewIndividualScoreInner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(pnlAdminViewIndividualScoreFrameLayout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(lblAdminViewIndividualScore, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAdminViewIndividualScoreFrameLayout.setVerticalGroup(
            pnlAdminViewIndividualScoreFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminViewIndividualScoreFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdminViewIndividualScoreFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLogout)
                    .addComponent(lblDisplayUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(188, 188, 188)
                .addComponent(pnlAdminViewIndividualScoreInner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminViewIndividualScoreFrameLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(lblAdminViewIndividualScore, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdminViewIndividualScoreFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdminViewIndividualScoreFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
        LoginFrame login=new LoginFrame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        // TODO add your handling code here:
        lblLogout.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        // TODO add your handling code here:
        lblLogout.setForeground(oldcolor);
    }//GEN-LAST:event_lblLogoutMouseExited

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ViewScoreFrame viewScore=new ViewScoreFrame();
        viewScore.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnBackActionPerformed

    private void txtPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPercentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPercentActionPerformed

    private void txtSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubjectActionPerformed
ArrayList<String>examList;
 String studentId;
    private void cbSelectStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSelectStudentActionPerformed
        // TODO add your handling code here:
       
//     if(cbSelectExam.getItemCount()>0)
//     {
//         cbSelectExam.removeAllItems();
//     }
    
     studentId=cbSelectStudent.getSelectedItem().toString();
        System.out.println("student "+studentId);
     try{
         cbSelectExam.removeAllItems();
         examList=PerformanceDAO.getExamList(studentId);
         for(String e:examList)
         {
             cbSelectExam.addItem(e);
             System.out.println("Exam name "+e);
         }
     }catch(SQLException ex)
     {
         JOptionPane.showMessageDialog(null,"!DB Error","ADMIN VIEW INDIVIDUAL SCORE",JOptionPane.ERROR_MESSAGE);
         ex.printStackTrace();
     }
     
     
       
      

    }//GEN-LAST:event_cbSelectStudentActionPerformed
 String examId;
    private void cbSelectExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSelectExamActionPerformed
        // TODO add your handling code here:
        
         
         try{
             examId=cbSelectExam.getSelectedItem().toString();
             StudentScore score=PerformanceDAO.getPerformanceDetatils(studentId, examId);
             txtSubject.setText(score.getSubject());
             txtPercent.setText(String.valueOf(score.getPerc()));
         }
         catch(SQLException ex)
     {
         JOptionPane.showMessageDialog(null,"!DB Error","ADMIN VIEW INDIVIDUAL SCORE",JOptionPane.ERROR_MESSAGE);
         ex.printStackTrace();
     }
     

        
        
    }//GEN-LAST:event_cbSelectExamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewIndividualScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewIndividualScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewIndividualScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewIndividualScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewIndividualScoreFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cbSelectExam;
    private javax.swing.JComboBox<String> cbSelectStudent;
    private javax.swing.JLabel lblAdminViewIndividualScore;
    private javax.swing.JLabel lblDisplayUsername;
    private javax.swing.JLabel lblExamId;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblPercentage;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblSelectStudent;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JPanel pnlAdminViewIndividualScoreFrame;
    private javax.swing.JPanel pnlAdminViewIndividualScoreInner;
    private javax.swing.JTextField txtPercent;
    private javax.swing.JTextField txtSubject;
    // End of variables declaration//GEN-END:variables
}
