/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuizApp_Gui;

import QuizApp_Pojo.UserProfile;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Sandarbh Taran
 */
public class AdminOptionFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminOptionFrame
     */
    
    Color oldcolor;
    public AdminOptionFrame() {
        initComponents();
        setLocationRelativeTo(null);
        lblDisplayUsername.setText("HELLO "+UserProfile.getUsername());
        oldcolor=lblLogout.getForeground();
        this.setTitle("QUIZAPP");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        AdminOptionPanel = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        lblAdminOptionFrame = new javax.swing.JLabel();
        pnlAdminOptionInner = new javax.swing.JPanel();
        rbSetPaper = new javax.swing.JRadioButton();
        rbEditPaper = new javax.swing.JRadioButton();
        rbRegisterStudent = new javax.swing.JRadioButton();
        btnDoTask = new javax.swing.JButton();
        rbChangePassword = new javax.swing.JRadioButton();
        rbViewScores = new javax.swing.JRadioButton();
        lblDisplayUsername = new javax.swing.JLabel();
        lblAdminImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        AdminOptionPanel.setBackground(new java.awt.Color(0, 0, 0));

        lblLogout.setBackground(new java.awt.Color(0, 0, 0));
        lblLogout.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 153, 51));
        lblLogout.setText("Logout");
        lblLogout.setOpaque(true);
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });

        lblAdminOptionFrame.setBackground(new java.awt.Color(0, 0, 0));
        lblAdminOptionFrame.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        lblAdminOptionFrame.setForeground(new java.awt.Color(0, 255, 0));
        lblAdminOptionFrame.setText("ADMINISTRATION SCREEN");

        pnlAdminOptionInner.setBackground(new java.awt.Color(0, 0, 0));
        pnlAdminOptionInner.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "MAKE A CHOICE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 3, 36), new java.awt.Color(0, 102, 102))); // NOI18N

        rbSetPaper.setBackground(new java.awt.Color(0, 0, 0));
        rbSetPaper.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        rbSetPaper.setForeground(new java.awt.Color(51, 51, 255));
        rbSetPaper.setText("SET PAPER");

        rbEditPaper.setBackground(new java.awt.Color(0, 0, 0));
        rbEditPaper.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        rbEditPaper.setForeground(new java.awt.Color(51, 51, 255));
        rbEditPaper.setText("EDIT PAPER");
        rbEditPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEditPaperActionPerformed(evt);
            }
        });

        rbRegisterStudent.setBackground(new java.awt.Color(0, 0, 0));
        rbRegisterStudent.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        rbRegisterStudent.setForeground(new java.awt.Color(51, 51, 255));
        rbRegisterStudent.setText("REGISTER USER");
        rbRegisterStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRegisterStudentActionPerformed(evt);
            }
        });

        btnDoTask.setBackground(new java.awt.Color(0, 0, 0));
        btnDoTask.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        btnDoTask.setForeground(new java.awt.Color(255, 153, 51));
        btnDoTask.setText("DO TASK");
        btnDoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoTaskActionPerformed(evt);
            }
        });

        rbChangePassword.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbChangePassword);
        rbChangePassword.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        rbChangePassword.setForeground(new java.awt.Color(51, 51, 255));
        rbChangePassword.setText("CHANGE PASSWORD");
        rbChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbChangePasswordActionPerformed(evt);
            }
        });

        rbViewScores.setBackground(new java.awt.Color(0, 0, 0));
        rbViewScores.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        rbViewScores.setForeground(new java.awt.Color(51, 51, 255));
        rbViewScores.setText("VIEW SCORES");
        rbViewScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbViewScoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminOptionInnerLayout = new javax.swing.GroupLayout(pnlAdminOptionInner);
        pnlAdminOptionInner.setLayout(pnlAdminOptionInnerLayout);
        pnlAdminOptionInnerLayout.setHorizontalGroup(
            pnlAdminOptionInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminOptionInnerLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(btnDoTask, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminOptionInnerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAdminOptionInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rbViewScores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbRegisterStudent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbSetPaper, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbEditPaper, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbChangePassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(168, 168, 168))
        );
        pnlAdminOptionInnerLayout.setVerticalGroup(
            pnlAdminOptionInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminOptionInnerLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(rbSetPaper)
                .addGap(18, 18, 18)
                .addComponent(rbEditPaper)
                .addGap(18, 18, 18)
                .addComponent(rbViewScores)
                .addGap(18, 18, 18)
                .addComponent(rbChangePassword)
                .addGap(18, 18, 18)
                .addComponent(rbRegisterStudent)
                .addGap(73, 73, 73)
                .addComponent(btnDoTask, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        lblDisplayUsername.setBackground(new java.awt.Color(0, 0, 0));
        lblDisplayUsername.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblDisplayUsername.setForeground(new java.awt.Color(0, 255, 0));

        lblAdminImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizApp_Gui/Images/AdminImage.png"))); // NOI18N
        lblAdminImage.setText("jLabel1");

        javax.swing.GroupLayout AdminOptionPanelLayout = new javax.swing.GroupLayout(AdminOptionPanel);
        AdminOptionPanel.setLayout(AdminOptionPanelLayout);
        AdminOptionPanelLayout.setHorizontalGroup(
            AdminOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminOptionPanelLayout.createSequentialGroup()
                .addGroup(AdminOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AdminOptionPanelLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(lblAdminOptionFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 214, Short.MAX_VALUE))
                    .addGroup(AdminOptionPanelLayout.createSequentialGroup()
                        .addGroup(AdminOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdminOptionPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblDisplayUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AdminOptionPanelLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(lblAdminImage, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(AdminOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlAdminOptionInner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        AdminOptionPanelLayout.setVerticalGroup(
            AdminOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminOptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDisplayUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAdminOptionFrame)
                .addGroup(AdminOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminOptionPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(pnlAdminOptionInner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(AdminOptionPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(lblAdminImage, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminOptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AdminOptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        // TODO add your handling code here:
        lblLogout.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        // TODO add your handling code here:
        lblLogout.setForeground(oldcolor);
    }//GEN-LAST:event_lblLogoutMouseExited

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
        LoginFrame login=new LoginFrame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void btnDoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoTaskActionPerformed
        // TODO add your handling code here:
        
        if(rbSetPaper.isSelected())
        {
            SetPaperFrame setPaper=new SetPaperFrame();
            setPaper.setVisible(true);
            
        }
        else if(rbEditPaper.isSelected())
        {
            EditPaperFrame editPaper=new EditPaperFrame();
            editPaper.setVisible(true);
         
        }
         else if(rbRegisterStudent.isSelected())
        {
            RegisterUserFrame registerUser=new RegisterUserFrame();
            registerUser.setVisible(true);
           
        }
         else  if(rbViewScores.isSelected())
        {
            ViewAllStudentsScoreFrame viewScore=new ViewAllStudentsScoreFrame();
            viewScore.setVisible(true);
           
        }
         
         else if(rbChangePassword.isSelected())
         {
             ChangePasswordFrame changePassword=new ChangePasswordFrame();
             changePassword.setVisible(true);
             
         }
        
        else
         {
             JOptionPane.showMessageDialog(null,"Please select a option","!!No selection", JOptionPane.ERROR_MESSAGE);
             return;
         }

        this.dispose();
        
    }//GEN-LAST:event_btnDoTaskActionPerformed

    private void rbChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbChangePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbChangePasswordActionPerformed

    private void rbEditPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEditPaperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEditPaperActionPerformed

    private void rbRegisterStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRegisterStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbRegisterStudentActionPerformed

    private void rbViewScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbViewScoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbViewScoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOptionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminOptionPanel;
    private javax.swing.JButton btnDoTask;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblAdminImage;
    private javax.swing.JLabel lblAdminOptionFrame;
    private javax.swing.JLabel lblDisplayUsername;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JPanel pnlAdminOptionInner;
    private javax.swing.JRadioButton rbChangePassword;
    private javax.swing.JRadioButton rbEditPaper;
    private javax.swing.JRadioButton rbRegisterStudent;
    private javax.swing.JRadioButton rbSetPaper;
    private javax.swing.JRadioButton rbViewScores;
    // End of variables declaration//GEN-END:variables
}
