/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuizApp_Gui;

import QuizApp_DAO.ExamDAO;
import QuizApp_Pojo.Exam;
import QuizApp_Pojo.UserProfile;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Sandarbh Taran
 */
public class EditPaperFrame extends javax.swing.JFrame {

    /**
     * Creates new form EditPaperFrame
     */
    String subjectName;
    Color oldcolor;
    public EditPaperFrame() {
        initComponents();
         lblDisplayUsername.setText("HELLO "+UserProfile.getUsername());
         oldcolor=lblLogout.getForeground();
         setLocationRelativeTo(null);
          this.setTitle("QUIZAPP");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        EditPaperPanel = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        lblEditPaperFrame = new javax.swing.JLabel();
        lblDisplayUsername = new javax.swing.JLabel();
        pnlSetPaperInner = new javax.swing.JPanel();
        cbSelectSubject = new javax.swing.JComboBox<>();
        cbExamId = new javax.swing.JComboBox<>();
        lblSelectPapaer = new javax.swing.JLabel();
        lblSelectExam = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnEdittQuestions = new javax.swing.JButton();
        lblSetQuestionImage1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        EditPaperPanel.setBackground(new java.awt.Color(0, 0, 0));

        lblLogout.setBackground(new java.awt.Color(0, 0, 0));
        lblLogout.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 153, 51));
        lblLogout.setText("Logout");
        lblLogout.setOpaque(true);
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });

        lblEditPaperFrame.setBackground(new java.awt.Color(0, 0, 0));
        lblEditPaperFrame.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        lblEditPaperFrame.setForeground(new java.awt.Color(0, 255, 0));
        lblEditPaperFrame.setText("PAPER EDITING SCREEN");

        lblDisplayUsername.setBackground(new java.awt.Color(0, 0, 0));
        lblDisplayUsername.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblDisplayUsername.setForeground(new java.awt.Color(0, 255, 0));

        pnlSetPaperInner.setBackground(new java.awt.Color(0, 0, 0));
        pnlSetPaperInner.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "PAPER DETAILS\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 3, 36), new java.awt.Color(0, 102, 102))); // NOI18N

        cbSelectSubject.setBackground(new java.awt.Color(204, 204, 204));
        cbSelectSubject.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        cbSelectSubject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "HINDI", "ENGLISH", "MATHEMATICS", "SOCIAL SCIENCE", "ECONOMICS", "HISTORY", "GEOGRAPHY", "SCIENCE", "PHYSICS", "CHEMISTRY", "BIOLOGY", "HTML", "CSS", "OBJECT ORIENTED PROGRAMMING", "C", "C++", "JAVA", "PYTHON", "DJANGO", "JAVASCRIPT", "KOTLIN", "ANDROID", "DATABASE MANAGEMENT SYSTEM", "OPERATION SYSTEM", "COMPUTER NETWORKING", " " }));
        cbSelectSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSelectSubjectActionPerformed(evt);
            }
        });

        cbExamId.setBackground(new java.awt.Color(204, 204, 204));
        cbExamId.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N

        lblSelectPapaer.setBackground(new java.awt.Color(0, 0, 0));
        lblSelectPapaer.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblSelectPapaer.setForeground(new java.awt.Color(255, 153, 51));
        lblSelectPapaer.setText("SELECT SUBJECT");

        lblSelectExam.setBackground(new java.awt.Color(0, 0, 0));
        lblSelectExam.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblSelectExam.setForeground(new java.awt.Color(255, 153, 51));
        lblSelectExam.setText("SELECT EXAM");

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 153, 51));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnEdittQuestions.setBackground(new java.awt.Color(0, 0, 0));
        btnEdittQuestions.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        btnEdittQuestions.setForeground(new java.awt.Color(255, 153, 51));
        btnEdittQuestions.setText("EDIT QUESTIONS");
        btnEdittQuestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdittQuestionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSetPaperInnerLayout = new javax.swing.GroupLayout(pnlSetPaperInner);
        pnlSetPaperInner.setLayout(pnlSetPaperInnerLayout);
        pnlSetPaperInnerLayout.setHorizontalGroup(
            pnlSetPaperInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSetPaperInnerLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(pnlSetPaperInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSelectExam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSelectPapaer)
                    .addComponent(cbSelectSubject, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbExamId, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
            .addGroup(pnlSetPaperInnerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(btnEdittQuestions)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSetPaperInnerLayout.setVerticalGroup(
            pnlSetPaperInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSetPaperInnerLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblSelectPapaer)
                .addGap(26, 26, 26)
                .addComponent(cbSelectSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblSelectExam)
                .addGap(36, 36, 36)
                .addComponent(cbExamId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(pnlSetPaperInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnEdittQuestions))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        lblSetQuestionImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizApp_Gui/Images/questionpaper.jpg"))); // NOI18N

        javax.swing.GroupLayout EditPaperPanelLayout = new javax.swing.GroupLayout(EditPaperPanel);
        EditPaperPanel.setLayout(EditPaperPanelLayout);
        EditPaperPanelLayout.setHorizontalGroup(
            EditPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditPaperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDisplayUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(EditPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditPaperPanelLayout.createSequentialGroup()
                        .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditPaperPanelLayout.createSequentialGroup()
                        .addComponent(lblEditPaperFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(218, 218, 218))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditPaperPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lblSetQuestionImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlSetPaperInner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        EditPaperPanelLayout.setVerticalGroup(
            EditPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditPaperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLogout)
                    .addGroup(EditPaperPanelLayout.createSequentialGroup()
                        .addComponent(lblDisplayUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addComponent(lblEditPaperFrame)
                .addGroup(EditPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditPaperPanelLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(pnlSetPaperInner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditPaperPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSetQuestionImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EditPaperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EditPaperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        // TODO add your handling code here:
        lblLogout.setForeground(Color.WHITE);
        
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        // TODO add your handling code here:
        lblLogout.setForeground(oldcolor);
    }//GEN-LAST:event_lblLogoutMouseExited

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
        
         LoginFrame login=new LoginFrame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLogoutMouseClicked

    private boolean validateInput()
    {
        int selectedIndex=cbSelectSubject.getSelectedIndex();
        if(selectedIndex==0)
        {
            return false;
        }
        subjectName=cbSelectSubject.getSelectedItem().toString();
        return true;
    }
    
    
    private void cbSelectSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSelectSubjectActionPerformed
        // TODO add your handling code here:
        
        boolean result=validateInput();
        if(!result)
        {
            JOptionPane.showMessageDialog(null,"Please select a subject","!!ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            ArrayList<String>examList=ExamDAO.getExamIdBySubject(subjectName);
            if(examList.isEmpty())
            {
                cbSelectSubject.setSelectedIndex(0);
               JOptionPane.showMessageDialog(null,"No  exam scheduled for the selected subject","!QUESTION SET NOT FOUND", JOptionPane.ERROR_MESSAGE);
            return; 
            }
            
            cbExamId.removeAllItems();
            for(String examId:examList)
            {
                cbExamId.addItem(examId);
            }
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,"DB Error","!!EDIT PAPER ERROR", JOptionPane.ERROR_MESSAGE);
          
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_cbSelectSubjectActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        AdminOptionFrame adminFrame=new AdminOptionFrame();
        adminFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEdittQuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdittQuestionsActionPerformed
        // TODO add your handling code here:
         boolean result=validateInput();
        if(!result)
        {
            JOptionPane.showMessageDialog(null,"Please select a subject","!!ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String subject=cbSelectSubject.getSelectedItem().toString();
        String examId=cbExamId.getSelectedItem().toString();
        int ans=JOptionPane.showConfirmDialog(null,"Are you sure your wanna edit "+examId+" of subject "+subject+" ?","CONFIRM?",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        {
            try{
                int totalQuestion=ExamDAO.getQuestionCountByExam(examId);
                Exam editExam=new Exam(examId,subject,totalQuestion);
                System.out.println("BEFORE EDITQUESTION FRame");
                EditQuestionFrame editQuestionFrame=new EditQuestionFrame(editExam);
                editQuestionFrame.setVisible(true);
                this.dispose();
            }
            catch(SQLException ex){
                 JOptionPane.showMessageDialog(null,"DB Error","!!EDIT PAPER ERROR", JOptionPane.ERROR_MESSAGE);
                 ex.printStackTrace();
            }
        }
        
        
       

    }//GEN-LAST:event_btnEdittQuestionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPaperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPaperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPaperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPaperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditPaperFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EditPaperPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdittQuestions;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbExamId;
    private javax.swing.JComboBox<String> cbSelectSubject;
    private javax.swing.JLabel lblDisplayUsername;
    private javax.swing.JLabel lblEditPaperFrame;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblSelectExam;
    private javax.swing.JLabel lblSelectPapaer;
    private javax.swing.JLabel lblSetQuestionImage1;
    private javax.swing.JPanel pnlSetPaperInner;
    // End of variables declaration//GEN-END:variables
}
