/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuizApp_Gui;

import QuizApp_DAO.ExamDAO;
import QuizApp_Pojo.Exam;
import QuizApp_Pojo.UserProfile;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Sandarbh Taran
 */
public class SetPaperFrame extends javax.swing.JFrame {

    /**
     * Creates new form SetPaperFrame
     */
    Color oldcolor;
    public SetPaperFrame() {
        initComponents();
        setLocationRelativeTo(null);
         lblDisplayUsername.setText("HELLO "+UserProfile.getUsername());
         oldcolor=lblLogout.getForeground();
         cbSelectSubject.setSelectedIndex(0);
         cbNoOfQuestions.setSelectedIndex(0);
          this.setTitle("QUIZAPP");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SetPaperPanel = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        SetPaperFrameLabel = new javax.swing.JLabel();
        lblDisplayUsername = new javax.swing.JLabel();
        pnlSetPaperInner = new javax.swing.JPanel();
        cbSelectSubject = new javax.swing.JComboBox<>();
        cbNoOfQuestions = new javax.swing.JComboBox<>();
        lblSelectPapaer = new javax.swing.JLabel();
        lblNoOfQuestions = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSetQuestions = new javax.swing.JButton();
        lblSetQuestionImage1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        SetPaperPanel.setBackground(new java.awt.Color(0, 0, 0));
        SetPaperPanel.setForeground(new java.awt.Color(255, 153, 51));

        lblLogout.setBackground(new java.awt.Color(0, 0, 0));
        lblLogout.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 153, 51));
        lblLogout.setText("Logout");
        lblLogout.setOpaque(true);
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });

        SetPaperFrameLabel.setBackground(new java.awt.Color(0, 0, 0));
        SetPaperFrameLabel.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        SetPaperFrameLabel.setForeground(new java.awt.Color(255, 153, 51));
        SetPaperFrameLabel.setText("SET PAPER");

        lblDisplayUsername.setBackground(new java.awt.Color(0, 0, 0));
        lblDisplayUsername.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblDisplayUsername.setForeground(new java.awt.Color(0, 255, 0));

        pnlSetPaperInner.setBackground(new java.awt.Color(0, 0, 0));
        pnlSetPaperInner.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "PAPER DETAILS\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 3, 36), new java.awt.Color(0, 102, 102))); // NOI18N

        cbSelectSubject.setBackground(new java.awt.Color(204, 204, 204));
        cbSelectSubject.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        cbSelectSubject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HINDI", "ENGLISH", "MATHEMATICS", "SOCIAL SCIENCE", "ECONOMICS", "HISTORY", "GEOGRAPHY", "SCIENCE", "PHYSICS", "CHEMISTRY", "BIOLOGY", "HTML", "CSS", "OBJECT ORIENTED PROGRAMMING", "C", "C++", "JAVA", "PYTHON", "DJANGO", "JAVASCRIPT", "KOTLIN", "ANDROID", "DATABASE MANAGEMENT SYSTEM", "OPERATION SYSTEM", "COMPUTER NETWORKING", " " }));
        cbSelectSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSelectSubjectActionPerformed(evt);
            }
        });

        cbNoOfQuestions.setBackground(new java.awt.Color(204, 204, 204));
        cbNoOfQuestions.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        cbNoOfQuestions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));

        lblSelectPapaer.setBackground(new java.awt.Color(0, 0, 0));
        lblSelectPapaer.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblSelectPapaer.setForeground(new java.awt.Color(255, 153, 51));
        lblSelectPapaer.setText("SELECT SUBJECT");

        lblNoOfQuestions.setBackground(new java.awt.Color(0, 0, 0));
        lblNoOfQuestions.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblNoOfQuestions.setForeground(new java.awt.Color(255, 153, 51));
        lblNoOfQuestions.setText("NO.OF QUESTIONS");

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 153, 51));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSetQuestions.setBackground(new java.awt.Color(0, 0, 0));
        btnSetQuestions.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        btnSetQuestions.setForeground(new java.awt.Color(255, 153, 51));
        btnSetQuestions.setText("SET QUESTIONS");
        btnSetQuestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetQuestionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSetPaperInnerLayout = new javax.swing.GroupLayout(pnlSetPaperInner);
        pnlSetPaperInner.setLayout(pnlSetPaperInnerLayout);
        pnlSetPaperInnerLayout.setHorizontalGroup(
            pnlSetPaperInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSetPaperInnerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlSetPaperInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNoOfQuestions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSelectPapaer)
                    .addComponent(cbSelectSubject, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbNoOfQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
            .addGroup(pnlSetPaperInnerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(btnSetQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSetPaperInnerLayout.setVerticalGroup(
            pnlSetPaperInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSetPaperInnerLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblSelectPapaer)
                .addGap(26, 26, 26)
                .addComponent(cbSelectSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblNoOfQuestions)
                .addGap(36, 36, 36)
                .addComponent(cbNoOfQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(pnlSetPaperInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnSetQuestions))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        lblSetQuestionImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizApp_Gui/Images/questionpaper.jpg"))); // NOI18N

        javax.swing.GroupLayout SetPaperPanelLayout = new javax.swing.GroupLayout(SetPaperPanel);
        SetPaperPanel.setLayout(SetPaperPanelLayout);
        SetPaperPanelLayout.setHorizontalGroup(
            SetPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SetPaperPanelLayout.createSequentialGroup()
                .addGroup(SetPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SetPaperPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDisplayUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SetPaperPanelLayout.createSequentialGroup()
                        .addContainerGap(74, Short.MAX_VALUE)
                        .addComponent(lblSetQuestionImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)))
                .addGroup(SetPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SetPaperPanelLayout.createSequentialGroup()
                        .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SetPaperPanelLayout.createSequentialGroup()
                        .addComponent(SetPaperFrameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(321, 321, 321))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SetPaperPanelLayout.createSequentialGroup()
                        .addComponent(pnlSetPaperInner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        SetPaperPanelLayout.setVerticalGroup(
            SetPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SetPaperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SetPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLogout)
                    .addGroup(SetPaperPanelLayout.createSequentialGroup()
                        .addComponent(lblDisplayUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addGap(28, 28, 28)
                .addComponent(SetPaperFrameLabel)
                .addGroup(SetPaperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SetPaperPanelLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(pnlSetPaperInner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SetPaperPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSetQuestionImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SetPaperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SetPaperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        // TODO add your handling code here:
        lblLogout.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        // TODO add your handling code here:
        lblLogout.setForeground(oldcolor);
    }//GEN-LAST:event_lblLogoutMouseExited

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
         LoginFrame login=new LoginFrame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void cbSelectSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSelectSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSelectSubjectActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        AdminOptionFrame adminFrame=new AdminOptionFrame();
        adminFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSetQuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetQuestionsActionPerformed
        // TODO add your handling code here:
        String subject=cbSelectSubject.getSelectedItem().toString();
        int total_question=Integer.parseInt(cbNoOfQuestions.getSelectedItem().toString());
        int ans=JOptionPane.showConfirmDialog(null,"You have selected\nSubject : "+subject+"\nNo.Of.Questions : "+total_question+"\nDo you wish continue?","CONFIRM?", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION)
        {
            try{
                String examid=ExamDAO.getExamId();
                Exam exam=new Exam(examid,subject,total_question);
                SetQuestionFrame setQuestion =new SetQuestionFrame(exam);
                setQuestion.setVisible(true);
                this.dispose();
            }catch(SQLException ex)
            {
                 JOptionPane.showMessageDialog(null,"DB ERROR ","!!!SET PAPER ERROR",JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_btnSetQuestionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetPaperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetPaperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetPaperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetPaperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetPaperFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SetPaperFrameLabel;
    private javax.swing.JPanel SetPaperPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSetQuestions;
    private javax.swing.JComboBox<String> cbNoOfQuestions;
    private javax.swing.JComboBox<String> cbSelectSubject;
    private javax.swing.JLabel lblDisplayUsername;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblNoOfQuestions;
    private javax.swing.JLabel lblSelectPapaer;
    private javax.swing.JLabel lblSetQuestionImage1;
    private javax.swing.JPanel pnlSetPaperInner;
    // End of variables declaration//GEN-END:variables
}
