/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuizApp_Gui;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Sandarbh Taran
 */
public class SplashScreenFrame extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreenFrame
     */
    public SplashScreenFrame() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        SplashScreenProgressBar.setStringPainted(true);
        SplashThread sp=new SplashThread();
        sp.start();
         this.setTitle("QUIZAPP");
    }
    
    class SplashThread extends Thread{
        public void run(){
            int count=1;
            Random r=new Random();
            while(SplashScreenProgressBar.getValue()<SplashScreenProgressBar.getMaximum()){
                try{
                    SplashScreenProgressBar.setValue(count);
                    Thread.sleep(1200);
                    count=count+r.nextInt(100);
                }
                catch(InterruptedException ex){
                    JOptionPane.showMessageDialog(null, "Exception in Thread:"+ex,"Error!",JOptionPane.ERROR_MESSAGE);
                }
            }
            
            LoginFrame loginFrame=new LoginFrame();
            loginFrame.setVisible(true);
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplashScreenPanel = new javax.swing.JPanel();
        SplashScreenProgressBar = new javax.swing.JProgressBar();
        lblSplashScreenImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        SplashScreenPanel.setBackground(new java.awt.Color(204, 255, 204));

        SplashScreenProgressBar.setBackground(new java.awt.Color(0, 102, 102));
        SplashScreenProgressBar.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        SplashScreenProgressBar.setForeground(new java.awt.Color(0, 0, 0));

        lblSplashScreenImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizApp_Gui/Images/SplashScreenImage.jpg"))); // NOI18N

        javax.swing.GroupLayout SplashScreenPanelLayout = new javax.swing.GroupLayout(SplashScreenPanel);
        SplashScreenPanel.setLayout(SplashScreenPanelLayout);
        SplashScreenPanelLayout.setHorizontalGroup(
            SplashScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SplashScreenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SplashScreenProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(SplashScreenPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblSplashScreenImage, javax.swing.GroupLayout.PREFERRED_SIZE, 1008, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SplashScreenPanelLayout.setVerticalGroup(
            SplashScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SplashScreenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSplashScreenImage, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SplashScreenProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplashScreenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SplashScreenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreenFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SplashScreenPanel;
    private javax.swing.JProgressBar SplashScreenProgressBar;
    private javax.swing.JLabel lblSplashScreenImage;
    // End of variables declaration//GEN-END:variables
}
