/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuizApp_Gui;

import QuizApp_Pojo.UserProfile;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Sandarbh Taran
 */
public class StudentOptionFrame extends javax.swing.JFrame {

    /**
     * Creates new form StudentOptionFrame
     */
    Color oldcolor;
    public StudentOptionFrame() {
        initComponents();
        setLocationRelativeTo(null);
        lblDisplayUsername.setText("HELLO "+UserProfile.getUsername());
        oldcolor=lblLogout.getForeground();
         this.setTitle("QUIZAPP");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentOptionPanel = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        lblStudentOptionFrame = new javax.swing.JLabel();
        pnlAdminOptionInner = new javax.swing.JPanel();
        rbTakeTest = new javax.swing.JRadioButton();
        rbChangePassword = new javax.swing.JRadioButton();
        rbViewScores = new javax.swing.JRadioButton();
        btnDoTask = new javax.swing.JButton();
        lblDisplayUsername = new javax.swing.JLabel();
        lblStudentImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        StudentOptionPanel.setBackground(new java.awt.Color(0, 0, 0));

        lblLogout.setBackground(new java.awt.Color(0, 0, 0));
        lblLogout.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 153, 51));
        lblLogout.setText("Logout");
        lblLogout.setOpaque(true);
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });

        lblStudentOptionFrame.setBackground(new java.awt.Color(0, 0, 0));
        lblStudentOptionFrame.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        lblStudentOptionFrame.setForeground(new java.awt.Color(0, 255, 0));
        lblStudentOptionFrame.setText("STUDENT  SCREEN");

        pnlAdminOptionInner.setBackground(new java.awt.Color(0, 0, 0));
        pnlAdminOptionInner.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "MAKE A CHOICE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 3, 36), new java.awt.Color(0, 102, 102))); // NOI18N

        rbTakeTest.setBackground(new java.awt.Color(0, 0, 0));
        rbTakeTest.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        rbTakeTest.setForeground(new java.awt.Color(51, 51, 255));
        rbTakeTest.setText("TAKE TEST");

        rbChangePassword.setBackground(new java.awt.Color(0, 0, 0));
        rbChangePassword.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        rbChangePassword.setForeground(new java.awt.Color(51, 51, 255));
        rbChangePassword.setText("CHANGE PASSWORD");

        rbViewScores.setBackground(new java.awt.Color(0, 0, 0));
        rbViewScores.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        rbViewScores.setForeground(new java.awt.Color(51, 51, 255));
        rbViewScores.setText("VIEW SCORES");

        btnDoTask.setBackground(new java.awt.Color(0, 0, 0));
        btnDoTask.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        btnDoTask.setForeground(new java.awt.Color(255, 153, 51));
        btnDoTask.setText("DO TASK");
        btnDoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminOptionInnerLayout = new javax.swing.GroupLayout(pnlAdminOptionInner);
        pnlAdminOptionInner.setLayout(pnlAdminOptionInnerLayout);
        pnlAdminOptionInnerLayout.setHorizontalGroup(
            pnlAdminOptionInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminOptionInnerLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(btnDoTask, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminOptionInnerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAdminOptionInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rbTakeTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbViewScores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(168, 168, 168))
        );
        pnlAdminOptionInnerLayout.setVerticalGroup(
            pnlAdminOptionInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminOptionInnerLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(rbTakeTest)
                .addGap(42, 42, 42)
                .addComponent(rbChangePassword)
                .addGap(39, 39, 39)
                .addComponent(rbViewScores)
                .addGap(57, 57, 57)
                .addComponent(btnDoTask, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        lblDisplayUsername.setBackground(new java.awt.Color(0, 0, 0));
        lblDisplayUsername.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblDisplayUsername.setForeground(new java.awt.Color(0, 255, 0));

        lblStudentImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizApp_Gui/Images/stud1.jpg"))); // NOI18N

        javax.swing.GroupLayout StudentOptionPanelLayout = new javax.swing.GroupLayout(StudentOptionPanel);
        StudentOptionPanel.setLayout(StudentOptionPanelLayout);
        StudentOptionPanelLayout.setHorizontalGroup(
            StudentOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentOptionPanelLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(lblStudentOptionFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(296, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentOptionPanelLayout.createSequentialGroup()
                .addGroup(StudentOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentOptionPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDisplayUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentOptionPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStudentImage, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(StudentOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAdminOptionInner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        StudentOptionPanelLayout.setVerticalGroup(
            StudentOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentOptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StudentOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLogout)
                    .addGroup(StudentOptionPanelLayout.createSequentialGroup()
                        .addComponent(lblDisplayUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addComponent(lblStudentOptionFrame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(StudentOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentOptionPanelLayout.createSequentialGroup()
                        .addComponent(pnlAdminOptionInner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentOptionPanelLayout.createSequentialGroup()
                        .addComponent(lblStudentImage, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentOptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StudentOptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        // TODO add your handling code here:
        lblLogout.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        // TODO add your handling code here:
        lblLogout.setForeground(oldcolor);
    }//GEN-LAST:event_lblLogoutMouseExited

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
         LoginFrame login=new LoginFrame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLogoutMouseClicked

    private boolean validateInput()
    {
        if(rbTakeTest.isSelected()==false&&rbChangePassword.isSelected()==false&&rbViewScores.isSelected()==false)
        { return false;}
        return true;
    }
    
    private void btnDoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoTaskActionPerformed
        // TODO add your handling code here:
        if(!validateInput())
                {
                    JOptionPane.showMessageDialog(null,"Please select a option","!!No selection", JOptionPane.ERROR_MESSAGE);
                    return;
                }
        if(rbTakeTest.isSelected())
        {
            PaperSelectionFrame selectPaperFrame=new PaperSelectionFrame();
            selectPaperFrame.setVisible(true);
        }
        
        else if(rbViewScores.isSelected())
        {
            ViewScoreFrame viewScore=new ViewScoreFrame();
            viewScore.setVisible(true);
           
        }
         
         else if(rbChangePassword.isSelected())
         {
             StudentsPasswordFrame changePassword=new StudentsPasswordFrame();
             changePassword.setVisible(true);
             
         }

        this.dispose();
    }//GEN-LAST:event_btnDoTaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentOptionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StudentOptionPanel;
    private javax.swing.JButton btnDoTask;
    private javax.swing.JLabel lblDisplayUsername;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblStudentImage;
    private javax.swing.JLabel lblStudentOptionFrame;
    private javax.swing.JPanel pnlAdminOptionInner;
    private javax.swing.JRadioButton rbChangePassword;
    private javax.swing.JRadioButton rbTakeTest;
    private javax.swing.JRadioButton rbViewScores;
    // End of variables declaration//GEN-END:variables
}
