/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuizApp_Gui;

import QuizApp_DAO.PerformanceDAO;
import QuizApp_Pojo.StudentScore;
import QuizApp_Pojo.UserProfile;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Sandarbh Taran
 */
public class StudentsIndividualScoreFrame extends javax.swing.JFrame {

    /**
     * Creates new form StudentsIndividualScoreFrame
     */
    Color oldcolor;
    ArrayList<String>examList;
    public StudentsIndividualScoreFrame() {
        initComponents();
        oldcolor=lblLogout.getForeground();
        setLocationRelativeTo(null);
        lblDisplayUsername.setText("Hello "+UserProfile.getUsername());
        getExamList();
       
        
    }
private void getExamList()
{
    try{
        examList=PerformanceDAO.getExamList(UserProfile.getUsername());
        if(examList.size()==0)
        {
            JOptionPane.showMessageDialog(null, "!!! You have not appeared for any test","!!TEST NOT GIVEN",JOptionPane.INFORMATION_MESSAGE);
                StudentOptionFrame studentFrame=new StudentOptionFrame();
                studentFrame.setVisible(true);
                this.dispose();
        }
        
        
        for(String exam:examList)
        {
            cbSelectExam.addItem(exam);
        }
        cbSelectExam.setSelectedIndex(0);
    }
    catch(SQLException ex)
    {
        ex.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlStudentsIndividualScore = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        lblViewIndividualScoreFrame = new javax.swing.JLabel();
        pnlStudentsIndividualScoreInner = new javax.swing.JPanel();
        lblExamId = new javax.swing.JLabel();
        lblSubject = new javax.swing.JLabel();
        lblPercentage = new javax.swing.JLabel();
        txtPercentage = new javax.swing.JTextField();
        txtSubject = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        cbSelectExam = new javax.swing.JComboBox<>();
        lblDisplayUsername = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlStudentsIndividualScore.setBackground(new java.awt.Color(0, 0, 0));

        lblLogout.setBackground(new java.awt.Color(0, 0, 0));
        lblLogout.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 153, 51));
        lblLogout.setText("Logout");
        lblLogout.setOpaque(true);
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });

        lblViewIndividualScoreFrame.setBackground(new java.awt.Color(204, 255, 204));
        lblViewIndividualScoreFrame.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        lblViewIndividualScoreFrame.setForeground(new java.awt.Color(0, 255, 0));
        lblViewIndividualScoreFrame.setText("STUDENTS PERFORMANCE");

        pnlStudentsIndividualScoreInner.setBackground(new java.awt.Color(0, 0, 0));
        pnlStudentsIndividualScoreInner.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "STUDENT'S SCORE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 3, 36), new java.awt.Color(0, 102, 102))); // NOI18N

        lblExamId.setBackground(new java.awt.Color(0, 0, 0));
        lblExamId.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblExamId.setForeground(new java.awt.Color(255, 153, 51));
        lblExamId.setText("SELECT EXAM ID");

        lblSubject.setBackground(new java.awt.Color(0, 0, 0));
        lblSubject.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblSubject.setForeground(new java.awt.Color(255, 153, 51));
        lblSubject.setText("SUBJECT");

        lblPercentage.setBackground(new java.awt.Color(0, 0, 0));
        lblPercentage.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblPercentage.setForeground(new java.awt.Color(255, 153, 51));
        lblPercentage.setText("PERCENTAGE");

        txtPercentage.setEditable(false);
        txtPercentage.setBackground(new java.awt.Color(204, 204, 204));
        txtPercentage.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N

        txtSubject.setEditable(false);
        txtSubject.setBackground(new java.awt.Color(204, 204, 204));
        txtSubject.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 153, 51));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        cbSelectExam.setBackground(new java.awt.Color(204, 204, 204));
        cbSelectExam.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        cbSelectExam.setForeground(new java.awt.Color(255, 153, 51));
        cbSelectExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSelectExamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStudentsIndividualScoreInnerLayout = new javax.swing.GroupLayout(pnlStudentsIndividualScoreInner);
        pnlStudentsIndividualScoreInner.setLayout(pnlStudentsIndividualScoreInnerLayout);
        pnlStudentsIndividualScoreInnerLayout.setHorizontalGroup(
            pnlStudentsIndividualScoreInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentsIndividualScoreInnerLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(pnlStudentsIndividualScoreInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudentsIndividualScoreInnerLayout.createSequentialGroup()
                        .addGroup(pnlStudentsIndividualScoreInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSubject, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblExamId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPercentage, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(58, 58, 58)
                        .addGroup(pnlStudentsIndividualScoreInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlStudentsIndividualScoreInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPercentage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSubject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbSelectExam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudentsIndividualScoreInnerLayout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200))))
        );
        pnlStudentsIndividualScoreInnerLayout.setVerticalGroup(
            pnlStudentsIndividualScoreInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentsIndividualScoreInnerLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(pnlStudentsIndividualScoreInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlStudentsIndividualScoreInnerLayout.createSequentialGroup()
                        .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(txtPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlStudentsIndividualScoreInnerLayout.createSequentialGroup()
                        .addGroup(pnlStudentsIndividualScoreInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblExamId)
                            .addComponent(cbSelectExam, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(lblSubject)
                        .addGap(57, 57, 57)
                        .addComponent(lblPercentage)))
                .addGap(59, 59, 59)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        lblDisplayUsername.setBackground(new java.awt.Color(0, 0, 0));
        lblDisplayUsername.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblDisplayUsername.setForeground(new java.awt.Color(0, 255, 0));

        lblScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizApp_Gui/Images/l&t-logo.PNG"))); // NOI18N

        javax.swing.GroupLayout pnlStudentsIndividualScoreLayout = new javax.swing.GroupLayout(pnlStudentsIndividualScore);
        pnlStudentsIndividualScore.setLayout(pnlStudentsIndividualScoreLayout);
        pnlStudentsIndividualScoreLayout.setHorizontalGroup(
            pnlStudentsIndividualScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentsIndividualScoreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDisplayUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(pnlStudentsIndividualScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudentsIndividualScoreLayout.createSequentialGroup()
                        .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudentsIndividualScoreLayout.createSequentialGroup()
                        .addComponent(lblViewIndividualScoreFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudentsIndividualScoreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(pnlStudentsIndividualScoreInner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlStudentsIndividualScoreLayout.setVerticalGroup(
            pnlStudentsIndividualScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudentsIndividualScoreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStudentsIndividualScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLogout)
                    .addGroup(pnlStudentsIndividualScoreLayout.createSequentialGroup()
                        .addComponent(lblDisplayUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addComponent(lblViewIndividualScoreFrame)
                .addGroup(pnlStudentsIndividualScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStudentsIndividualScoreLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(pnlStudentsIndividualScoreInner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudentsIndividualScoreLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlStudentsIndividualScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlStudentsIndividualScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
        LoginFrame login=new LoginFrame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        // TODO add your handling code here:
        lblLogout.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        // TODO add your handling code here:
        lblLogout.setForeground(oldcolor);
    }//GEN-LAST:event_lblLogoutMouseExited

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
             ViewScoreFrame viewScore=new ViewScoreFrame();
       viewScore.setVisible(true);
       this.dispose();
        

    }//GEN-LAST:event_btnBackActionPerformed

    private void cbSelectExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSelectExamActionPerformed
        // TODO add your handling code here:
        String ExamId=cbSelectExam.getSelectedItem().toString();
        try{
            StudentScore score=PerformanceDAO.getPerformanceDetatils(UserProfile.getUsername(), ExamId);
            txtSubject.setText(score.getSubject());
            txtPercentage.setText(String.valueOf(score.getPerc()));
        }catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "!!! DB Error","!! STUDENTS INDIVIDUAL SCORE GET PERFORMANCE DETAILS ERROR",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_cbSelectExamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentsIndividualScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentsIndividualScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentsIndividualScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentsIndividualScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentsIndividualScoreFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cbSelectExam;
    private javax.swing.JLabel lblDisplayUsername;
    private javax.swing.JLabel lblExamId;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblPercentage;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblViewIndividualScoreFrame;
    private javax.swing.JPanel pnlStudentsIndividualScore;
    private javax.swing.JPanel pnlStudentsIndividualScoreInner;
    private javax.swing.JTextField txtPercentage;
    private javax.swing.JTextField txtSubject;
    // End of variables declaration//GEN-END:variables
}
