/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuizApp_Gui;

import QuizApp_DAO.PerformanceDAO;
import QuizApp_DAO.QuestionDAO;
import QuizApp_Pojo.Answer;
import QuizApp_Pojo.AnswerStore;
import QuizApp_Pojo.Exam;
import QuizApp_Pojo.Performance;
import QuizApp_Pojo.Question;
import QuizApp_Pojo.QuestionStore;
import QuizApp_Pojo.UserProfile;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Sandarbh Taran
 */
public class TakeTestFrame extends javax.swing.JFrame {

    /**
     * Creates new form TakeTestFrame
     */
    Color oldcolor;
    private int qno,pos;
    private QuestionStore qstore;
    private AnswerStore astore;
    private Exam exam;
    public TakeTestFrame() {
        initComponents();
        setLocationRelativeTo(null);
        lblDisplayUsername.setText("HELLO "+UserProfile.getUsername());
        oldcolor=lblLogout.getForeground();
         this.setTitle("QUIZAPP");
         System.out.println("Constructor ");
        qstore=new QuestionStore();
        astore=new AnswerStore();
        qno=1;
        
    }
    
    public TakeTestFrame(Exam exam1)
    {
        this();
        this.exam=exam1;
        System.out.println(exam);
        lblTakeTestFrame.setText(exam.getSubject().toUpperCase()+" PAPER");
        loadQuestion();
        showQuestion();
         System.out.println("Constructor para");
    }
    
     private void loadQuestion()
    {System.out.println("Loading");
        try{
            ArrayList<Question>questionList=QuestionDAO.getQuestionsByExamId(exam.getExamId());
            System.out.println(exam.getExamId());
            qstore=new QuestionStore();
            System.out.println("QUESTIONLIST"+questionList);
            for(Question q:questionList)
            {
                System.out.println(q);
                qstore.addQuestion(q);
            }
            System.out.println(qstore.getAllQuestions());
        }catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,"DB Error","EDIT QUESTION ERROR!",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
     
     private void showQuestion()
    { System.out.println("Showing");
        
        Question q=qstore.getQuestion(pos);
        buttonGroup1.clearSelection();
        txtareaQuestion.setText(q.getQuestion());
        rbOption1.setText(q.getOption1());
        rbOption2.setText(q.getOption2());
        rbOption3.setText(q.getOption3());
        rbOption4.setText(q.getOption4());
       Answer ans=astore.getAnswerByQno(qno);
       if(ans==null)
       {
           return ;
       }
       
       String str=ans.getChoosenAnswer();
       switch(str)
         {
               case"Option1":case"option1":
               rbOption1.setSelected(true);
               break;
               case"Option2":case"option2":
               rbOption2.setSelected(true);
               break;
               case"Option3":case"option3":
               rbOption3.setSelected(true);
               break;
               case"Option4":case"option4":
               rbOption4.setSelected(true);
               break;
               
           
         }
    }
     
     
     private String getUserAnswer()
     {
         if(rbOption1.isSelected())
             return "option1";
         else if(rbOption2.isSelected())
             return "option2";
         
         else if(rbOption3.isSelected())
             return "option3";
          
         else if(rbOption4.isSelected())
             return "option4";
         else return null;
     }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        TakeTestPanel = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        lblTakeTestFrame = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbOption1 = new javax.swing.JRadioButton();
        rbOption3 = new javax.swing.JRadioButton();
        rbOption2 = new javax.swing.JRadioButton();
        rbOption4 = new javax.swing.JRadioButton();
        btnPrevious = new javax.swing.JButton();
        btnDone = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaQuestion = new javax.swing.JTextArea();
        lblQno = new javax.swing.JLabel();
        lblDisplayUsername = new javax.swing.JLabel();
        lblTakeTestImage = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        TakeTestPanel.setBackground(new java.awt.Color(0, 0, 0));

        lblLogout.setBackground(new java.awt.Color(0, 0, 0));
        lblLogout.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 153, 51));
        lblLogout.setText("Logout");
        lblLogout.setOpaque(true);
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });

        lblTakeTestFrame.setBackground(new java.awt.Color(204, 255, 204));
        lblTakeTestFrame.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        lblTakeTestFrame.setForeground(new java.awt.Color(0, 102, 102));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        rbOption1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbOption1);
        rbOption1.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        rbOption1.setForeground(new java.awt.Color(51, 51, 255));

        rbOption3.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbOption3);
        rbOption3.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        rbOption3.setForeground(new java.awt.Color(51, 51, 255));

        rbOption2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbOption2);
        rbOption2.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        rbOption2.setForeground(new java.awt.Color(51, 51, 255));

        rbOption4.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbOption4);
        rbOption4.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        rbOption4.setForeground(new java.awt.Color(51, 51, 255));
        rbOption4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOption4ActionPerformed(evt);
            }
        });

        btnPrevious.setBackground(new java.awt.Color(0, 0, 0));
        btnPrevious.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        btnPrevious.setForeground(new java.awt.Color(255, 153, 51));
        btnPrevious.setText("PREVIOUS");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnDone.setBackground(new java.awt.Color(0, 0, 0));
        btnDone.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        btnDone.setForeground(new java.awt.Color(255, 153, 51));
        btnDone.setText("DONE");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 153, 51));
        jButton3.setText("CANCEL");

        btnNext.setBackground(new java.awt.Color(0, 0, 0));
        btnNext.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 153, 51));
        btnNext.setText("NEXT");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        txtareaQuestion.setEditable(false);
        txtareaQuestion.setBackground(new java.awt.Color(204, 204, 204));
        txtareaQuestion.setColumns(20);
        txtareaQuestion.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        txtareaQuestion.setRows(5);
        jScrollPane1.setViewportView(txtareaQuestion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbOption1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbOption3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rbOption2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbOption4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblQno, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOption1)
                    .addComponent(rbOption2))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbOption3)
                    .addComponent(rbOption4))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevious)
                    .addComponent(btnDone)
                    .addComponent(jButton3)
                    .addComponent(btnNext))
                .addGap(30, 30, 30))
        );

        lblDisplayUsername.setBackground(new java.awt.Color(0, 0, 0));
        lblDisplayUsername.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblDisplayUsername.setForeground(new java.awt.Color(0, 255, 0));

        lblTakeTestImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizApp_Gui/Images/docicon.png"))); // NOI18N
        lblTakeTestImage.setText("jLabel1");

        javax.swing.GroupLayout TakeTestPanelLayout = new javax.swing.GroupLayout(TakeTestPanel);
        TakeTestPanel.setLayout(TakeTestPanelLayout);
        TakeTestPanelLayout.setHorizontalGroup(
            TakeTestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TakeTestPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TakeTestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TakeTestPanelLayout.createSequentialGroup()
                        .addGroup(TakeTestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TakeTestPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblTakeTestFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(167, 167, 167))
                            .addGroup(TakeTestPanelLayout.createSequentialGroup()
                                .addComponent(lblDisplayUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TakeTestPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTakeTestImage, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(399, 399, 399))
        );
        TakeTestPanelLayout.setVerticalGroup(
            TakeTestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TakeTestPanelLayout.createSequentialGroup()
                .addGroup(TakeTestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TakeTestPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblTakeTestFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TakeTestPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogout))
                    .addComponent(lblDisplayUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblTakeTestImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TakeTestPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TakeTestPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbOption4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOption4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOption4ActionPerformed

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        // TODO add your handling code here:
        lblLogout.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        // TODO add your handling code here:
        lblLogout.setForeground(oldcolor);
    }//GEN-LAST:event_lblLogoutMouseExited

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
         LoginFrame login=new LoginFrame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        
        String choosenAnswer=getUserAnswer();
        if(choosenAnswer!=null)
        {
            
            Question quest=qstore.getQuestionByQno(qno);
            String correctAnswer=quest.getCorrectAnswer();
            Answer ans=new Answer(exam.getExamId(),exam.getSubject(),qno,correctAnswer,choosenAnswer);
            Answer attempted=astore.getAnswerByQno(qno);
            if(attempted==null)
            {
                 astore.addAnswer(ans);
            }
            else{
                String PreviousAnswer=attempted.getChoosenAnswer();
                if(PreviousAnswer.equals(choosenAnswer))
                {
                    int apos=astore.removeAnswer(attempted);
                    astore.setAnswer(apos, ans);
                }
            }
        }
         pos++;
        if(pos>=qstore.getCount())
        {
            pos=0;
        }
        
        qno++;
        if(qno>qstore.getCount())
            qno=1;
        lblQno.setText("Question no : "+qno);
        showQuestion();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
          String choosenAnswer=getUserAnswer();
        if(choosenAnswer!=null)
        {
            Question quest=qstore.getQuestionByQno(qno);
            String correctAnswer=quest.getCorrectAnswer();
            Answer ans=new Answer(exam.getExamId(),exam.getSubject(),qno,correctAnswer,choosenAnswer);
            Answer attempted=astore.getAnswerByQno(qno);
            if(attempted==null)
            {
                 astore.addAnswer(ans);
            }
            else{
                String PreviousAnswer=attempted.getChoosenAnswer();
                if(PreviousAnswer.equals(choosenAnswer))
                {
                    int apos=astore.removeAnswer(attempted);
                    astore.setAnswer(apos, ans);
                }
            }
        }
         pos--;
        if(pos<0)
        {
            pos=qstore.getCount()-1;
        }
        
        qno--;
        if(qno<=0)
            qno=qstore.getCount();
        lblQno.setText("Question no : "+qno);
        showQuestion();
        
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        // TODO add your handling code here:
        String choosenAnswer=getUserAnswer();
        if(choosenAnswer!=null)
        {
            Question quest=qstore.getQuestionByQno(qno);
            String correctAnswer=quest.getCorrectAnswer();
            Answer ans=new Answer(exam.getExamId(),exam.getSubject(),qno,correctAnswer,choosenAnswer);
            Answer attempted=astore.getAnswerByQno(qno);
            if(attempted==null)
            {
                 astore.addAnswer(ans);
            }
            else{
                String PreviousAnswer=attempted.getChoosenAnswer();
                if(PreviousAnswer.equals(choosenAnswer))
                {
                    int apos=astore.removeAnswer(attempted);
                    astore.setAnswer(apos, ans);
                }
            }
        }
        int right=0,wrong=0;
        for(Question quest:qstore.getAllQuestions())
        {
            int qno=quest.getQno();
            Answer ans=astore.getAnswerByQno(qno);
            if(ans==null)
            {continue;}
            String attemptedAnswer=ans.getChoosenAnswer();
            String correctAnswer=ans.getCorrectAnswer();
            System.out.println("Correct ans= "+correctAnswer+" choosenAnswer = "+attemptedAnswer);
            if(attemptedAnswer.equals(correctAnswer))
            {++right;}
            else 
            {++wrong;}
        }
        StringBuilder sb=new StringBuilder();
        sb.append("\nRight Answers "+right);
        sb.append("\nWrong Answers "+wrong);
        sb.append("\nUnattempted Answers "+(qstore.getCount()-(right+wrong)));
        JOptionPane.showMessageDialog(null,sb.toString(),"RESULT",JOptionPane.INFORMATION_MESSAGE);
        
        try{
            Performance perf=new Performance(exam.getExamId(),exam.getSubject(),UserProfile.getUsername(),right,wrong,(qstore.getCount()-(right+wrong)),((double)right/qstore.getCount()*100));
            PerformanceDAO.addPerformance(perf);
            JOptionPane.showMessageDialog(null,"Result saved successfully\nThank you for attending/attempting the test","PERFORMANCE SAVED",JOptionPane.INFORMATION_MESSAGE);
            StudentOptionFrame studentFrame=new StudentOptionFrame();
            studentFrame.setVisible(true);
            this.dispose();
            
        }catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,"DB Error","!TAKE TEST ERROR",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnDoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakeTestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TakeTestPanel;
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDisplayUsername;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblQno;
    private javax.swing.JLabel lblTakeTestFrame;
    private javax.swing.JLabel lblTakeTestImage;
    private javax.swing.JRadioButton rbOption1;
    private javax.swing.JRadioButton rbOption2;
    private javax.swing.JRadioButton rbOption3;
    private javax.swing.JRadioButton rbOption4;
    private javax.swing.JTextArea txtareaQuestion;
    // End of variables declaration//GEN-END:variables
}
