/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuizApp_Gui;

import QuizApp_Pojo.UserProfile;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Sandarbh Taran
 */
public class ViewScoreFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewScoreFrame
     */
    Color oldcolor;
    public ViewScoreFrame() {
        initComponents();
        setLocationRelativeTo(null);
        lblDisplayUsername.setText("HELLO "+UserProfile.getUsername());
        oldcolor=lblLogout.getForeground();
         this.setTitle("QUIZAPP");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        ViewScorePanel = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        lblViewScoreFrame = new javax.swing.JLabel();
        pnlViewScoreInner = new javax.swing.JPanel();
        rbViewIndividualScore = new javax.swing.JRadioButton();
        rbViewAllScores = new javax.swing.JRadioButton();
        btnViewScore = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblDisplayUsername = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        ViewScorePanel.setBackground(new java.awt.Color(0, 0, 0));
        ViewScorePanel.setForeground(new java.awt.Color(255, 153, 51));

        lblLogout.setBackground(new java.awt.Color(0, 0, 0));
        lblLogout.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 153, 51));
        lblLogout.setText("Logout");
        lblLogout.setOpaque(true);
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });

        lblViewScoreFrame.setBackground(new java.awt.Color(0, 0, 0));
        lblViewScoreFrame.setFont(new java.awt.Font("Cambria", 3, 48)); // NOI18N
        lblViewScoreFrame.setForeground(new java.awt.Color(0, 255, 0));
        lblViewScoreFrame.setText("RECORDS");

        pnlViewScoreInner.setBackground(new java.awt.Color(0, 0, 0));
        pnlViewScoreInner.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "MAKE A CHOICE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 3, 24), new java.awt.Color(0, 102, 102))); // NOI18N
        pnlViewScoreInner.setForeground(new java.awt.Color(255, 153, 51));

        rbViewIndividualScore.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbViewIndividualScore);
        rbViewIndividualScore.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        rbViewIndividualScore.setForeground(new java.awt.Color(51, 51, 255));
        rbViewIndividualScore.setText("VIEW STUDENTS PERFORMANCE");

        rbViewAllScores.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rbViewAllScores);
        rbViewAllScores.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        rbViewAllScores.setForeground(new java.awt.Color(51, 51, 255));
        rbViewAllScores.setText("VIEW ALL RECORDS");
        rbViewAllScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbViewAllScoresActionPerformed(evt);
            }
        });

        btnViewScore.setBackground(new java.awt.Color(0, 0, 0));
        btnViewScore.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        btnViewScore.setForeground(new java.awt.Color(255, 153, 51));
        btnViewScore.setText("VIEW SCORE");
        btnViewScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewScoreActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 153, 51));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlViewScoreInnerLayout = new javax.swing.GroupLayout(pnlViewScoreInner);
        pnlViewScoreInner.setLayout(pnlViewScoreInnerLayout);
        pnlViewScoreInnerLayout.setHorizontalGroup(
            pnlViewScoreInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlViewScoreInnerLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewScore, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
            .addGroup(pnlViewScoreInnerLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(pnlViewScoreInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rbViewIndividualScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbViewAllScores, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlViewScoreInnerLayout.setVerticalGroup(
            pnlViewScoreInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewScoreInnerLayout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(rbViewIndividualScore)
                .addGap(47, 47, 47)
                .addComponent(rbViewAllScores)
                .addGap(94, 94, 94)
                .addGroup(pnlViewScoreInnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewScore)
                    .addComponent(btnBack))
                .addGap(71, 71, 71))
        );

        lblDisplayUsername.setBackground(new java.awt.Color(0, 0, 0));
        lblDisplayUsername.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblDisplayUsername.setForeground(new java.awt.Color(0, 255, 0));

        lblScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizApp_Gui/Images/l&t-logo.PNG"))); // NOI18N

        javax.swing.GroupLayout ViewScorePanelLayout = new javax.swing.GroupLayout(ViewScorePanel);
        ViewScorePanel.setLayout(ViewScorePanelLayout);
        ViewScorePanelLayout.setHorizontalGroup(
            ViewScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewScorePanelLayout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addComponent(lblViewScoreFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ViewScorePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViewScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewScorePanelLayout.createSequentialGroup()
                        .addComponent(lblDisplayUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 718, Short.MAX_VALUE)
                        .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewScorePanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblScore)
                        .addGap(18, 18, 18)
                        .addComponent(pnlViewScoreInner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ViewScorePanelLayout.setVerticalGroup(
            ViewScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewScorePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViewScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLogout)
                    .addGroup(ViewScorePanelLayout.createSequentialGroup()
                        .addComponent(lblDisplayUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addGap(40, 40, 40)
                .addComponent(lblViewScoreFrame)
                .addGroup(ViewScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewScorePanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(pnlViewScoreInner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewScorePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblScore)
                        .addGap(180, 180, 180))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ViewScorePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ViewScorePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbViewAllScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbViewAllScoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbViewAllScoresActionPerformed

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        // TODO add your handling code here:
        lblLogout.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        // TODO add your handling code here:
        lblLogout.setForeground(oldcolor);
    }//GEN-LAST:event_lblLogoutMouseExited

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        // TODO add your handling code here:
         LoginFrame login=new LoginFrame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblLogoutMouseClicked

   
    

    private void btnViewScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewScoreActionPerformed
        // TODO add your handling code here:
        
        if(rbViewIndividualScore.isSelected()==true)
        {
             if(UserProfile.getUserType().equalsIgnoreCase("STUDENT")==true)
            {
                StudentsIndividualScoreFrame studentIndividualScore=new StudentsIndividualScoreFrame();
            studentIndividualScore.setVisible(true);
            this.dispose();
            }
            
        }
            
        else if(rbViewAllScores.isSelected()==true)
        {
             if(UserProfile.getUserType().equalsIgnoreCase("ADMIN")==true)
        {
           ViewAllStudentsScoreFrame viewAllScore=new ViewAllStudentsScoreFrame();
            viewAllScore.setVisible(true);
            this.dispose();
        }
             else if(UserProfile.getUserType().equalsIgnoreCase("STUDENT")==true)
            {
                StudentsIndividualAllScoreFrame studentIndividualAllScore=new StudentsIndividualAllScoreFrame();
            studentIndividualAllScore.setVisible(true);
            this.dispose();
            }
            
        }
        
        else
        {
            JOptionPane.showMessageDialog(null,"Please select an option","NO OPTION SELECTED",JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnViewScoreActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        String userType=UserProfile.getUserType();
        if(userType==null)
        {
             JOptionPane.showMessageDialog(null,"!Sorry cannot go back.\nYour are not a valid user","!INVALID USER",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(userType.equalsIgnoreCase("ADMIN"))
        {
            AdminOptionFrame adminFrame=new AdminOptionFrame();
            adminFrame.setVisible(true);
            this.dispose();
        }
        
        else if(UserProfile.getUserType().equalsIgnoreCase("STUDENT"))
        {
            StudentOptionFrame studentFrame=new StudentOptionFrame();
            studentFrame.setVisible(true);
            this.dispose();
        }
        
        
        
        
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewScoreFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewScoreFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ViewScorePanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewScore;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblDisplayUsername;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblViewScoreFrame;
    private javax.swing.JPanel pnlViewScoreInner;
    private javax.swing.JRadioButton rbViewAllScores;
    private javax.swing.JRadioButton rbViewIndividualScore;
    // End of variables declaration//GEN-END:variables
}
